// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Metadata of a BranchRule. BranchRule is the protection rule to enforce
/// pre-defined rules on designated branches within a repository.
public struct BranchRule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. A unique identifier for a BranchRule. The name should be of the
  /// format:
  /// `projects/{project}/locations/{location}/repositories/{repository}/branchRules/{branch_rule}`
  public var name: Swift.String = Swift.String()

  /// Output only. Unique identifier of the repository.
  public var uid: Swift.String = Swift.String()

  /// Output only. Create timestamp.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. Update timestamp.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Optional. User annotations. These attributes can only be set and used by
  /// the user. See https://google.aip.dev/128#annotations for more details such
  /// as format and size limitations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. This checksum is computed by the server based on the value of
  /// other fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. The pattern of the branch that can match to this BranchRule.
  /// Specified as regex.
  /// .* for all branches. Examples: main, (main|release.*).
  /// Current MVP phase only support `.*` for wildcard.
  public var includePattern: Swift.String = Swift.String()

  /// Optional. Determines if the branch rule is disabled or not.
  public var disabled: Swift.Bool = Swift.Bool()

  /// Optional. Determines if the branch rule requires a pull request or not.
  public var requirePullRequest: Swift.Bool = Swift.Bool()

  /// Optional. The minimum number of reviews required for the branch rule to be
  /// matched.
  public var minimumReviewsCount: Swift.Int32 = Swift.Int32()

  /// Optional. The minimum number of approvals required for the branch rule to
  /// be matched.
  public var minimumApprovalsCount: Swift.Int32 = Swift.Int32()

  /// Optional. Determines if code owners must approve before merging to the
  /// branch.
  public var requireCodeOwnerApproval: Swift.Bool = Swift.Bool()

  /// Optional. Determines if require comments resolved before merging to the
  /// branch.
  public var requireCommentsResolved: Swift.Bool = Swift.Bool()

  /// Optional. Determines if allow stale reviews or approvals before merging to
  /// the branch.
  public var allowStaleReviews: Swift.Bool = Swift.Bool()

  /// Optional. Determines if require linear history before merging to the
  /// branch.
  public var requireLinearHistory: Swift.Bool = Swift.Bool()

  /// Optional. List of required status checks before merging to the branch.
  public var requiredStatusChecks: [BranchRule.Check] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BranchRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BranchRule().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let etag = CodingKeys(stringValue: "etag")
    static let includePattern = CodingKeys(stringValue: "includePattern")
    static let disabled = CodingKeys(stringValue: "disabled")
    static let requirePullRequest = CodingKeys(stringValue: "requirePullRequest")
    static let minimumReviewsCount = CodingKeys(stringValue: "minimumReviewsCount")
    static let minimumApprovalsCount = CodingKeys(stringValue: "minimumApprovalsCount")
    static let requireCodeOwnerApproval = CodingKeys(stringValue: "requireCodeOwnerApproval")
    static let requireCommentsResolved = CodingKeys(stringValue: "requireCommentsResolved")
    static let allowStaleReviews = CodingKeys(stringValue: "allowStaleReviews")
    static let requireLinearHistory = CodingKeys(stringValue: "requireLinearHistory")
    static let requiredStatusChecks = CodingKeys(stringValue: "requiredStatusChecks")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "createTime",
      "updateTime",
      "annotations",
      "etag",
      "includePattern",
      "disabled",
      "requirePullRequest",
      "minimumReviewsCount",
      "minimumApprovalsCount",
      "requireCodeOwnerApproval",
      "requireCommentsResolved",
      "allowStaleReviews",
      "requireLinearHistory",
      "requiredStatusChecks",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .includePattern) {
      self.includePattern = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
      self.disabled = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requirePullRequest) {
      self.requirePullRequest = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minimumReviewsCount) {
      self.minimumReviewsCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minimumApprovalsCount) {
      self.minimumApprovalsCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requireCodeOwnerApproval)
    {
      self.requireCodeOwnerApproval = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requireCommentsResolved)
    {
      self.requireCommentsResolved = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowStaleReviews) {
      self.allowStaleReviews = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requireLinearHistory) {
      self.requireLinearHistory = value
    }
    if let value = try container.decodeIfPresent(
      [BranchRule.Check].self, forKey: .requiredStatusChecks)
    {
      self.requiredStatusChecks = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.includePattern, forKey: .includePattern)
    try container.encode(self.disabled, forKey: .disabled)
    try container.encode(self.requirePullRequest, forKey: .requirePullRequest)
    try container.encode(self.minimumReviewsCount, forKey: .minimumReviewsCount)
    try container.encode(self.minimumApprovalsCount, forKey: .minimumApprovalsCount)
    try container.encode(self.requireCodeOwnerApproval, forKey: .requireCodeOwnerApproval)
    try container.encode(self.requireCommentsResolved, forKey: .requireCommentsResolved)
    try container.encode(self.allowStaleReviews, forKey: .allowStaleReviews)
    try container.encode(self.requireLinearHistory, forKey: .requireLinearHistory)
    try container.encode(self.requiredStatusChecks, forKey: .requiredStatusChecks)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Check is a type for status check.
  public struct Check: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The context of the check.
    public var context: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Check`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Check().with { $0.context = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let context = CodingKeys(stringValue: "context")

      static let _knownKeys: Set<Swift.String> = [
        "context"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .context) {
        self.context = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.context, forKey: .context)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securesourcemanager.v1.BranchRule.Check"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securesourcemanager.v1.BranchRule"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
