// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Metadata of a BranchRule. BranchRule is the protection rule to enforce
/// pre-defined rules on designated branches within a repository.
public struct BranchRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. A unique identifier for a BranchRule. The name should be of the
  /// format:
  /// `projects/{project}/locations/{location}/repositories/{repository}/branchRules/{branch_rule}`
  public var name: Swift.String = Swift.String()

  /// Output only. Unique identifier of the repository.
  public var uid: Swift.String = Swift.String()

  /// Output only. Create timestamp.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Update timestamp.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. User annotations. These attributes can only be set and used by
  /// the user. See https://google.aip.dev/128#annotations for more details such
  /// as format and size limitations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. This checksum is computed by the server based on the value of
  /// other fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. The pattern of the branch that can match to this BranchRule.
  /// Specified as regex.
  /// .* for all branches. Examples: main, (main|release.*).
  /// Current MVP phase only support `.*` for wildcard.
  public var includePattern: Swift.String = Swift.String()

  /// Optional. Determines if the branch rule is disabled or not.
  public var disabled: Swift.Bool = Swift.Bool()

  /// Optional. Determines if the branch rule requires a pull request or not.
  public var requirePullRequest: Swift.Bool = Swift.Bool()

  /// Optional. The minimum number of reviews required for the branch rule to be
  /// matched.
  public var minimumReviewsCount: Swift.Int32 = Swift.Int32()

  /// Optional. The minimum number of approvals required for the branch rule to
  /// be matched.
  public var minimumApprovalsCount: Swift.Int32 = Swift.Int32()

  /// Optional. Determines if code owners must approve before merging to the
  /// branch.
  public var requireCodeOwnerApproval: Swift.Bool = Swift.Bool()

  /// Optional. Determines if require comments resolved before merging to the
  /// branch.
  public var requireCommentsResolved: Swift.Bool = Swift.Bool()

  /// Optional. Determines if allow stale reviews or approvals before merging to
  /// the branch.
  public var allowStaleReviews: Swift.Bool = Swift.Bool()

  /// Optional. Determines if require linear history before merging to the
  /// branch.
  public var requireLinearHistory: Swift.Bool = Swift.Bool()

  /// Optional. List of required status checks before merging to the branch.
  public var requiredStatusChecks: [BranchRule.Check] = []

  /// Initialize a new instance of `BranchRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BranchRule().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Check is a type for status check.
  public struct Check: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The context of the check.
    public var context: Swift.String = Swift.String()

    /// Initialize a new instance of `Check`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Check().with { $0.context = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securesourcemanager.v1.BranchRule.Check"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securesourcemanager.v1.BranchRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
