// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for fetching a tree structure from a repository.
public struct FetchTreeRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The format is
  /// `projects/{project_number}/locations/{location_id}/repositories/{repository_id}`.
  /// Specifies the repository to fetch the tree from.
  public var repository: Swift.String = Swift.String()

  /// Optional. `ref` can be a SHA-1 hash, a branch name, or a tag. Specifies
  /// which tree to fetch. If not specified, the default branch will be used.
  public var ref: Swift.String = Swift.String()

  /// Optional. If true, include all subfolders and their files in the response.
  /// If false, only the immediate children are returned.
  public var recursive: Swift.Bool = Swift.Bool()

  /// Optional. Requested page size.  Server may return fewer items than
  /// requested. If unspecified, at most 10,000 items will be returned.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token identifying a page of results the server should return.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `FetchTreeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchTreeRequest().with { $0.repository = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securesourcemanager.v1.FetchTreeRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
