// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A resource that represents a Secure Source Manager instance.
public struct Instance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. A unique identifier for an instance. The name should be of the
  /// format:
  /// `projects/{project_number}/locations/{location_id}/instances/{instance_id}`
  ///
  /// `project_number`: Maps to a unique int64 id assigned to each project.
  ///
  /// `location_id`: Refers to the region where the instance will be deployed.
  /// Since Secure Source Manager is a regional service, it must be one of the
  /// valid GCP regions.
  ///
  /// `instance_id`: User provided name for the instance, must be unique for a
  /// project_number and location_id combination.
  public var name: Swift.String = Swift.String()

  /// Output only. Create timestamp.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Update timestamp.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Labels as key value pairs.
  /// Keys and values can contain only lowercase letters, numeric characters,
  /// underscores, and dashes.
  /// For more information, see [Requirements for
  /// labels](https://cloud.google.com/resource-manager/docs/best-practices-labels#label_encoding).
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Private settings for private instance.
  public var privateConfig: Instance.PrivateConfig? = nil

  /// Output only. Current state of the instance.
  public var state: Instance.State = Instance.State()

  /// Output only. An optional field providing information about the current
  /// instance state.
  public var stateNote: Instance.StateNote = Instance.StateNote()

  /// Optional. Immutable. Customer-managed encryption key name, in the format
  /// projects/*/locations/*/keyRings/*/cryptoKeys/*.
  public var kmsKey: Swift.String = Swift.String()

  /// Output only. A list of hostnames for this instance.
  public var hostConfig: Instance.HostConfig? = nil

  /// Optional. Configuration for Workforce Identity Federation to support
  /// third party identity provider. If unset, defaults to the Google OIDC IdP.
  public var workforceIdentityFederationConfig: Instance.WorkforceIdentityFederationConfig? = nil

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// HostConfig has different instance endpoints.
  public struct HostConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. HTML hostname.
    public var html: Swift.String = Swift.String()

    /// Output only. API hostname.
    public var api: Swift.String = Swift.String()

    /// Output only. Git HTTP hostname.
    public var gitHttp: Swift.String = Swift.String()

    /// Output only. Git SSH hostname.
    public var gitSsh: Swift.String = Swift.String()

    /// Initialize a new instance of `HostConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = HostConfig().with { $0.html = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securesourcemanager.v1.Instance.HostConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// PrivateConfig includes settings for private instance.
  public struct PrivateConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Immutable. Indicate if it's private instance.
    public var isPrivate: Swift.Bool = Swift.Bool()

    /// Optional. Immutable. CA pool resource, resource must in the format of
    /// `projects/{project}/locations/{location}/caPools/{ca_pool}`.
    public var caPool: Swift.String = Swift.String()

    /// Output only. Service Attachment for HTTP, resource is in the format of
    /// `projects/{project}/regions/{region}/serviceAttachments/{service_attachment}`.
    public var httpServiceAttachment: Swift.String = Swift.String()

    /// Output only. Service Attachment for SSH, resource is in the format of
    /// `projects/{project}/regions/{region}/serviceAttachments/{service_attachment}`.
    public var sshServiceAttachment: Swift.String = Swift.String()

    /// Optional. Additional allowed projects for setting up PSC connections.
    /// Instance host project is automatically allowed and does not need to be
    /// included in this list.
    public var pscAllowedProjects: [Swift.String] = []

    /// Optional. Custom host config for the instance.
    public var customHostConfig: Instance.PrivateConfig.CustomHostConfig? = nil

    /// Initialize a new instance of `PrivateConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PrivateConfig().with { $0.isPrivate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Custom host config for the instance.
    public struct CustomHostConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. The custom UI hostname for the instance, e.g.,
      /// "git.source.internal.mycompany.com"
      public var html: Swift.String = Swift.String()

      /// Required. The custom API hostname for the instance, e.g.,
      /// "api.source.internal.mycompany.com"
      public var api: Swift.String = Swift.String()

      /// Required. The custom git ssh hostname for the instance, e.g.,
      /// "ssh.source.internal.mycompany.com"
      public var gitSsh: Swift.String = Swift.String()

      /// Required. The custom git http hostname for the instance, e.g.,
      /// "git.source.internal.mycompany.com"
      public var gitHttp: Swift.String = Swift.String()

      /// Initialize a new instance of `CustomHostConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = CustomHostConfig().with { $0.html = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.securesourcemanager.v1.Instance.PrivateConfig.CustomHostConfig"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securesourcemanager.v1.Instance.PrivateConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// WorkforceIdentityFederationConfig allows this instance to support users
  /// from external identity providers.
  public struct WorkforceIdentityFederationConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Immutable. Whether Workforce Identity Federation is enabled.
    public var enabled: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `WorkforceIdentityFederationConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = WorkforceIdentityFederationConfig().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.securesourcemanager.v1.Instance.WorkforceIdentityFederationConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Secure Source Manager instance state.
  public enum State: Codable, Equatable, Sendable {
    /// Not set. This should only be the case for incoming requests.
    case unspecified
    /// Instance is being created.
    case creating
    /// Instance is ready.
    case active
    /// Instance is being deleted.
    case deleting
    /// Instance is paused.
    case paused
    /// Instance is unknown, we are not sure if it's functioning.
    case unknown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .deleting: return 3
      case .paused: return 4
      case .unknown: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .paused: return "PAUSED"
      case .unknown: return "UNKNOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      case "PAUSED": self = .paused
      case "UNKNOWN": self = .unknown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .deleting
      case 4: self = .paused
      case 6: self = .unknown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .paused: return try container.encode(4)
      case .unknown: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Provides information about the current instance state.
  public enum StateNote: Codable, Equatable, Sendable {
    /// STATE_NOTE_UNSPECIFIED as the first value of State.
    case unspecified
    /// CMEK access is unavailable.
    case pausedCmekUnavailable
    /// INSTANCE_RESUMING indicates that the instance was previously paused
    /// and is under the process of being brought back.
    @available(*, deprecated)
    case instanceResuming
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pausedCmekUnavailable: return 1
      case .instanceResuming: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_NOTE_UNSPECIFIED"
      case .pausedCmekUnavailable: return "PAUSED_CMEK_UNAVAILABLE"
      case .instanceResuming: return "INSTANCE_RESUMING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:StateNote/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_NOTE_UNSPECIFIED": self = .unspecified
      case "PAUSED_CMEK_UNAVAILABLE": self = .pausedCmekUnavailable
      case "INSTANCE_RESUMING": self = .instanceResuming
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:StateNote/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pausedCmekUnavailable
      case 2: self = .instanceResuming
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pausedCmekUnavailable: return try container.encode(1)
      case .instanceResuming: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securesourcemanager.v1.Instance"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
