// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// PullRequestComment represents a comment on a pull request.
public struct PullRequestComment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Unique identifier for the pull request comment. The comment id
  /// is generated by the server. Format:
  /// `projects/{project}/locations/{location}/repositories/{repository}/pullRequests/{pull_request}/pullRequestComments/{comment_id}`
  public var name: Swift.String = Swift.String()

  /// Output only. Creation timestamp.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Last updated timestamp.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// The comment detail. A comment can be a review, a general comment, or a
  /// code comment.
  public var commentDetail: OneOf_CommentDetail? = nil

  /// Initialize a new instance of `PullRequestComment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PullRequestComment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case review = "review"
    case comment = "comment"
    case code = "code"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)

    var commentDetail: OneOf_CommentDetail? = nil
    let commentDetailCheckAndSet = {
      if commentDetail != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'commentDetail'"))
      }
      commentDetail = $0
    }
    if let review = try container.decodeIfPresent(PullRequestComment.Review?.self, forKey: .review)
    {
      try commentDetailCheckAndSet(.review(review))
    }
    if let comment = try container.decodeIfPresent(
      PullRequestComment.Comment?.self, forKey: .comment)
    {
      try commentDetailCheckAndSet(.comment(comment))
    }
    if let code = try container.decodeIfPresent(PullRequestComment.Code?.self, forKey: .code) {
      try commentDetailCheckAndSet(.code(code))
    }
    self.commentDetail = commentDetail
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)

    if let choice = self.commentDetail {
      switch choice {
      case .review(let value):
        try container.encode(value, forKey: .review)
      case .comment(let value):
        try container.encode(value, forKey: .comment)
      case .code(let value):
        try container.encode(value, forKey: .code)
      }
    }
  }

  /// The review summary comment.
  public struct Review: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The review action type.
    public var actionType: PullRequestComment.Review.ActionType = PullRequestComment.Review
      .ActionType()

    /// Optional. The comment body.
    public var body: Swift.String = Swift.String()

    /// Output only. The effective commit sha this review is pointing to.
    public var effectiveCommitSha: Swift.String = Swift.String()

    /// Initialize a new instance of `Review`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Review().with { $0.actionType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The review action type.
    public enum ActionType: Codable, Equatable, Sendable {
      /// Unspecified.
      case unspecified
      /// A general review comment.
      case comment
      /// Change required from this review.
      case changeRequested
      /// Change approved from this review.
      case approved
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .comment: return 1
        case .changeRequested: return 2
        case .approved: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "ACTION_TYPE_UNSPECIFIED"
        case .comment: return "COMMENT"
        case .changeRequested: return "CHANGE_REQUESTED"
        case .approved: return "APPROVED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ActionType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ACTION_TYPE_UNSPECIFIED": self = .unspecified
        case "COMMENT": self = .comment
        case "CHANGE_REQUESTED": self = .changeRequested
        case "APPROVED": self = .approved
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ActionType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .comment
        case 2: self = .changeRequested
        case 3: self = .approved
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .comment: return try container.encode(1)
        case .changeRequested: return try container.encode(2)
        case .approved: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securesourcemanager.v1.PullRequestComment.Review"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The general pull request comment.
  public struct Comment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The comment body.
    public var body: Swift.String = Swift.String()

    /// Initialize a new instance of `Comment`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Comment().with { $0.body = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securesourcemanager.v1.PullRequestComment.Comment"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The comment on a code line.
  public struct Code: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The comment body.
    public var body: Swift.String = Swift.String()

    /// Optional. Input only. The PullRequestComment resource name that this
    /// comment is replying to.
    public var reply: Swift.String = Swift.String()

    /// Optional. The position of the comment.
    public var position: PullRequestComment.Position? = nil

    /// Output only. The root comment of the conversation, derived from the reply
    /// field.
    public var effectiveRootComment: Swift.String = Swift.String()

    /// Output only. Boolean indicator if the comment is resolved.
    public var resolved: Swift.Bool = Swift.Bool()

    /// Output only. The effective commit sha this code comment is pointing to.
    public var effectiveCommitSha: Swift.String = Swift.String()

    /// Initialize a new instance of `Code`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Code().with { $0.body = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securesourcemanager.v1.PullRequestComment.Code"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The position of the code comment.
  public struct Position: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The path of the file.
    public var path: Swift.String = Swift.String()

    /// Required. The line number of the comment. Positive value means it's on
    /// the new side of the diff, negative value means it's on the old side.
    public var line: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `Position`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Position().with { $0.path = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securesourcemanager.v1.PullRequestComment.Position"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The comment detail. A comment can be a review, a general comment, or a
  /// code comment.
  public enum OneOf_CommentDetail: Codable, Equatable, Sendable {
    /// Optional. The review summary comment.
    indirect case review(PullRequestComment.Review?)
    /// Optional. The general pull request comment.
    indirect case comment(PullRequestComment.Comment?)
    /// Optional. The comment on a code line.
    indirect case code(PullRequestComment.Code?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securesourcemanager.v1.PullRequestComment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
