// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol SecureSourceManagerStub: Sendable {
    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListInstancesResponse

    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Instance

    func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRepositories(
      request: ListRepositoriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListRepositoriesResponse

    func getRepository(
      request: GetRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Repository

    func createRepository(
      request: CreateRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateRepository(
      request: UpdateRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteRepository(
      request: DeleteRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listHooks(
      request: ListHooksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListHooksResponse

    func getHook(
      request: GetHookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Hook

    func createHook(
      request: CreateHookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateHook(
      request: UpdateHookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteHook(
      request: DeleteHookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getIamPolicyRepo(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func setIamPolicyRepo(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissionsRepo(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func createBranchRule(
      request: CreateBranchRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listBranchRules(
      request: ListBranchRulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListBranchRulesResponse

    func getBranchRule(
      request: GetBranchRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.BranchRule

    func updateBranchRule(
      request: UpdateBranchRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteBranchRule(
      request: DeleteBranchRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createPullRequest(
      request: CreatePullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getPullRequest(
      request: GetPullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.PullRequest

    func listPullRequests(
      request: ListPullRequestsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListPullRequestsResponse

    func updatePullRequest(
      request: UpdatePullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func mergePullRequest(
      request: MergePullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func openPullRequest(
      request: OpenPullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func closePullRequest(
      request: ClosePullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listPullRequestFileDiffs(
      request: ListPullRequestFileDiffsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListPullRequestFileDiffsResponse

    func fetchTree(
      request: FetchTreeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.FetchTreeResponse

    func fetchBlob(
      request: FetchBlobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.FetchBlobResponse

    func fetchRefs(
      request: FetchRefsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.FetchRefsResponse

    func createIssue(
      request: CreateIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getIssue(
      request: GetIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Issue

    func listIssues(
      request: ListIssuesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListIssuesResponse

    func updateIssue(
      request: UpdateIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteIssue(
      request: DeleteIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func openIssue(
      request: OpenIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func closeIssue(
      request: CloseIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getPullRequestComment(
      request: GetPullRequestCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.PullRequestComment

    func listPullRequestComments(
      request: ListPullRequestCommentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListPullRequestCommentsResponse

    func createPullRequestComment(
      request: CreatePullRequestCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updatePullRequestComment(
      request: UpdatePullRequestCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deletePullRequestComment(
      request: DeletePullRequestCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func batchCreatePullRequestComments(
      request: BatchCreatePullRequestCommentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func resolvePullRequestComments(
      request: ResolvePullRequestCommentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func unresolvePullRequestComments(
      request: UnresolvePullRequestCommentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createIssueComment(
      request: CreateIssueCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getIssueComment(
      request: GetIssueCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.IssueComment

    func listIssueComments(
      request: ListIssueCommentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListIssueCommentsResponse

    func updateIssueComment(
      request: UpdateIssueCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteIssueComment(
      request: DeleteIssueCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
