// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class SecureSourceManagerRetry: SecureSourceManagerStub {
    let inner: any SecureSourceManagerStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any SecureSourceManagerStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListInstancesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListInstancesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListInstancesResponse
          in
          return try await self.inner.listInstances(request: r, options: o)
        })
    }

    public func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Instance {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.Instance
          in
          return try await self.inner.getInstance(request: r, options: o)
        })
    }

    public func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createInstance(request: r, options: o)
        })
    }

    public func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteInstance(request: r, options: o)
        })
    }

    public func listRepositories(
      request: ListRepositoriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListRepositoriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListRepositoriesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListRepositoriesResponse
          in
          return try await self.inner.listRepositories(request: r, options: o)
        })
    }

    public func getRepository(
      request: GetRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Repository {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetRepositoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.Repository
          in
          return try await self.inner.getRepository(request: r, options: o)
        })
    }

    public func createRepository(
      request: CreateRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateRepositoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createRepository(request: r, options: o)
        })
    }

    public func updateRepository(
      request: UpdateRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateRepositoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateRepository(request: r, options: o)
        })
    }

    public func deleteRepository(
      request: DeleteRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteRepositoryRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteRepository(request: r, options: o)
        })
    }

    public func listHooks(
      request: ListHooksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListHooksResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListHooksRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListHooksResponse
          in
          return try await self.inner.listHooks(request: r, options: o)
        })
    }

    public func getHook(
      request: GetHookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Hook {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetHookRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.Hook
          in
          return try await self.inner.getHook(request: r, options: o)
        })
    }

    public func createHook(
      request: CreateHookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateHookRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createHook(request: r, options: o)
        })
    }

    public func updateHook(
      request: UpdateHookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateHookRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateHook(request: r, options: o)
        })
    }

    public func deleteHook(
      request: DeleteHookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteHookRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteHook(request: r, options: o)
        })
    }

    public func getIamPolicyRepo(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicyRepo(request: r, options: o)
        })
    }

    public func setIamPolicyRepo(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicyRepo(request: r, options: o)
        })
    }

    public func testIamPermissionsRepo(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissionsRepo(request: r, options: o)
        })
    }

    public func createBranchRule(
      request: CreateBranchRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBranchRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBranchRule(request: r, options: o)
        })
    }

    public func listBranchRules(
      request: ListBranchRulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListBranchRulesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBranchRulesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListBranchRulesResponse
          in
          return try await self.inner.listBranchRules(request: r, options: o)
        })
    }

    public func getBranchRule(
      request: GetBranchRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.BranchRule {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBranchRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.BranchRule
          in
          return try await self.inner.getBranchRule(request: r, options: o)
        })
    }

    public func updateBranchRule(
      request: UpdateBranchRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBranchRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBranchRule(request: r, options: o)
        })
    }

    public func deleteBranchRule(
      request: DeleteBranchRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteBranchRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBranchRule(request: r, options: o)
        })
    }

    public func createPullRequest(
      request: CreatePullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreatePullRequestRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPullRequest(request: r, options: o)
        })
    }

    public func getPullRequest(
      request: GetPullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.PullRequest {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPullRequestRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.PullRequest
          in
          return try await self.inner.getPullRequest(request: r, options: o)
        })
    }

    public func listPullRequests(
      request: ListPullRequestsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListPullRequestsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPullRequestsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListPullRequestsResponse
          in
          return try await self.inner.listPullRequests(request: r, options: o)
        })
    }

    public func updatePullRequest(
      request: UpdatePullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdatePullRequestRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePullRequest(request: r, options: o)
        })
    }

    public func mergePullRequest(
      request: MergePullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: MergePullRequestRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.mergePullRequest(request: r, options: o)
        })
    }

    public func openPullRequest(
      request: OpenPullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: OpenPullRequestRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.openPullRequest(request: r, options: o)
        })
    }

    public func closePullRequest(
      request: ClosePullRequestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ClosePullRequestRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.closePullRequest(request: r, options: o)
        })
    }

    public func listPullRequestFileDiffs(
      request: ListPullRequestFileDiffsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListPullRequestFileDiffsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPullRequestFileDiffsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListPullRequestFileDiffsResponse
          in
          return try await self.inner.listPullRequestFileDiffs(request: r, options: o)
        })
    }

    public func fetchTree(
      request: FetchTreeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.FetchTreeResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchTreeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.FetchTreeResponse
          in
          return try await self.inner.fetchTree(request: r, options: o)
        })
    }

    public func fetchBlob(
      request: FetchBlobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.FetchBlobResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchBlobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.FetchBlobResponse
          in
          return try await self.inner.fetchBlob(request: r, options: o)
        })
    }

    public func createIssue(
      request: CreateIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateIssueRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createIssue(request: r, options: o)
        })
    }

    public func getIssue(
      request: GetIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Issue {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetIssueRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.Issue
          in
          return try await self.inner.getIssue(request: r, options: o)
        })
    }

    public func listIssues(
      request: ListIssuesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListIssuesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListIssuesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListIssuesResponse
          in
          return try await self.inner.listIssues(request: r, options: o)
        })
    }

    public func updateIssue(
      request: UpdateIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateIssueRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateIssue(request: r, options: o)
        })
    }

    public func deleteIssue(
      request: DeleteIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteIssueRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteIssue(request: r, options: o)
        })
    }

    public func openIssue(
      request: OpenIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: OpenIssueRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.openIssue(request: r, options: o)
        })
    }

    public func closeIssue(
      request: CloseIssueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CloseIssueRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.closeIssue(request: r, options: o)
        })
    }

    public func getPullRequestComment(
      request: GetPullRequestCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.PullRequestComment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPullRequestCommentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.PullRequestComment
          in
          return try await self.inner.getPullRequestComment(request: r, options: o)
        })
    }

    public func listPullRequestComments(
      request: ListPullRequestCommentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListPullRequestCommentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPullRequestCommentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListPullRequestCommentsResponse
          in
          return try await self.inner.listPullRequestComments(request: r, options: o)
        })
    }

    public func createPullRequestComment(
      request: CreatePullRequestCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreatePullRequestCommentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPullRequestComment(request: r, options: o)
        })
    }

    public func updatePullRequestComment(
      request: UpdatePullRequestCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdatePullRequestCommentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePullRequestComment(request: r, options: o)
        })
    }

    public func deletePullRequestComment(
      request: DeletePullRequestCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeletePullRequestCommentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePullRequestComment(request: r, options: o)
        })
    }

    public func batchCreatePullRequestComments(
      request: BatchCreatePullRequestCommentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchCreatePullRequestCommentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchCreatePullRequestComments(request: r, options: o)
        })
    }

    public func resolvePullRequestComments(
      request: ResolvePullRequestCommentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ResolvePullRequestCommentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.resolvePullRequestComments(request: r, options: o)
        })
    }

    public func unresolvePullRequestComments(
      request: UnresolvePullRequestCommentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UnresolvePullRequestCommentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.unresolvePullRequestComments(request: r, options: o)
        })
    }

    public func createIssueComment(
      request: CreateIssueCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateIssueCommentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createIssueComment(request: r, options: o)
        })
    }

    public func getIssueComment(
      request: GetIssueCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.IssueComment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetIssueCommentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.IssueComment
          in
          return try await self.inner.getIssueComment(request: r, options: o)
        })
    }

    public func listIssueComments(
      request: ListIssueCommentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListIssueCommentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListIssueCommentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListIssueCommentsResponse
          in
          return try await self.inner.listIssueComments(request: r, options: o)
        })
    }

    public func updateIssueComment(
      request: UpdateIssueCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateIssueCommentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateIssueComment(request: r, options: o)
        })
    }

    public func deleteIssueComment(
      request: DeleteIssueCommentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteIssueCommentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteIssueComment(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
