// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class SecureSourceManagerLogging: SecureSourceManagerStub {
    let inner: any SecureSourceManagerStub
    let logger: Logger

    public init(_ inner: any SecureSourceManagerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-securesourcemanager-v1"
      logger[metadataKey: "gcp.client.service"] = "securesourcemanager"
      logger[metadataKey: "gcp.experimental.swift.client"] = "SecureSourceManager"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listInstances(
      request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListInstancesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listInstances",
        action: {
          (r: ListInstancesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListInstancesResponse
          in
          return try await self.inner.listInstances(request: r, options: o)
        })
    }

    public func getInstance(
      request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Instance {
      try await self._intercept(
        request: request,
        options: options,
        name: "getInstance",
        action: {
          (r: GetInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.Instance
          in
          return try await self.inner.getInstance(request: r, options: o)
        })
    }

    public func createInstance(
      request: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createInstance",
        action: {
          (r: CreateInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createInstance(request: r, options: o)
        })
    }

    public func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteInstance",
        action: {
          (r: DeleteInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteInstance(request: r, options: o)
        })
    }

    public func listRepositories(
      request: ListRepositoriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListRepositoriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRepositories",
        action: {
          (r: ListRepositoriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListRepositoriesResponse
          in
          return try await self.inner.listRepositories(request: r, options: o)
        })
    }

    public func getRepository(
      request: GetRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Repository {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRepository",
        action: {
          (r: GetRepositoryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.Repository
          in
          return try await self.inner.getRepository(request: r, options: o)
        })
    }

    public func createRepository(
      request: CreateRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createRepository",
        action: {
          (r: CreateRepositoryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createRepository(request: r, options: o)
        })
    }

    public func updateRepository(
      request: UpdateRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateRepository",
        action: {
          (r: UpdateRepositoryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateRepository(request: r, options: o)
        })
    }

    public func deleteRepository(
      request: DeleteRepositoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteRepository",
        action: {
          (r: DeleteRepositoryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteRepository(request: r, options: o)
        })
    }

    public func listHooks(
      request: ListHooksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListHooksResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listHooks",
        action: {
          (r: ListHooksRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListHooksResponse
          in
          return try await self.inner.listHooks(request: r, options: o)
        })
    }

    public func getHook(
      request: GetHookRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Hook {
      try await self._intercept(
        request: request,
        options: options,
        name: "getHook",
        action: {
          (r: GetHookRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.Hook
          in
          return try await self.inner.getHook(request: r, options: o)
        })
    }

    public func createHook(
      request: CreateHookRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createHook",
        action: {
          (r: CreateHookRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createHook(request: r, options: o)
        })
    }

    public func updateHook(
      request: UpdateHookRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateHook",
        action: {
          (r: UpdateHookRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateHook(request: r, options: o)
        })
    }

    public func deleteHook(
      request: DeleteHookRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteHook",
        action: {
          (r: DeleteHookRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteHook(request: r, options: o)
        })
    }

    public func getIamPolicyRepo(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicyRepo",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicyRepo(request: r, options: o)
        })
    }

    public func setIamPolicyRepo(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicyRepo",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicyRepo(request: r, options: o)
        })
    }

    public func testIamPermissionsRepo(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissionsRepo",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissionsRepo(request: r, options: o)
        })
    }

    public func createBranchRule(
      request: CreateBranchRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBranchRule",
        action: {
          (r: CreateBranchRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBranchRule(request: r, options: o)
        })
    }

    public func listBranchRules(
      request: ListBranchRulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListBranchRulesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBranchRules",
        action: {
          (r: ListBranchRulesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListBranchRulesResponse
          in
          return try await self.inner.listBranchRules(request: r, options: o)
        })
    }

    public func getBranchRule(
      request: GetBranchRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.BranchRule {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBranchRule",
        action: {
          (r: GetBranchRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.BranchRule
          in
          return try await self.inner.getBranchRule(request: r, options: o)
        })
    }

    public func updateBranchRule(
      request: UpdateBranchRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBranchRule",
        action: {
          (r: UpdateBranchRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBranchRule(request: r, options: o)
        })
    }

    public func deleteBranchRule(
      request: DeleteBranchRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBranchRule",
        action: {
          (r: DeleteBranchRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBranchRule(request: r, options: o)
        })
    }

    public func createPullRequest(
      request: CreatePullRequestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPullRequest",
        action: {
          (r: CreatePullRequestRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPullRequest(request: r, options: o)
        })
    }

    public func getPullRequest(
      request: GetPullRequestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.PullRequest {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPullRequest",
        action: {
          (r: GetPullRequestRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.PullRequest
          in
          return try await self.inner.getPullRequest(request: r, options: o)
        })
    }

    public func listPullRequests(
      request: ListPullRequestsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListPullRequestsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPullRequests",
        action: {
          (r: ListPullRequestsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListPullRequestsResponse
          in
          return try await self.inner.listPullRequests(request: r, options: o)
        })
    }

    public func updatePullRequest(
      request: UpdatePullRequestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePullRequest",
        action: {
          (r: UpdatePullRequestRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePullRequest(request: r, options: o)
        })
    }

    public func mergePullRequest(
      request: MergePullRequestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "mergePullRequest",
        action: {
          (r: MergePullRequestRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.mergePullRequest(request: r, options: o)
        })
    }

    public func openPullRequest(
      request: OpenPullRequestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "openPullRequest",
        action: {
          (r: OpenPullRequestRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.openPullRequest(request: r, options: o)
        })
    }

    public func closePullRequest(
      request: ClosePullRequestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "closePullRequest",
        action: {
          (r: ClosePullRequestRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.closePullRequest(request: r, options: o)
        })
    }

    public func listPullRequestFileDiffs(
      request: ListPullRequestFileDiffsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListPullRequestFileDiffsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPullRequestFileDiffs",
        action: {
          (r: ListPullRequestFileDiffsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListPullRequestFileDiffsResponse
          in
          return try await self.inner.listPullRequestFileDiffs(request: r, options: o)
        })
    }

    public func fetchTree(
      request: FetchTreeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.FetchTreeResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchTree",
        action: {
          (r: FetchTreeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.FetchTreeResponse
          in
          return try await self.inner.fetchTree(request: r, options: o)
        })
    }

    public func fetchBlob(
      request: FetchBlobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.FetchBlobResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchBlob",
        action: {
          (r: FetchBlobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.FetchBlobResponse
          in
          return try await self.inner.fetchBlob(request: r, options: o)
        })
    }

    public func createIssue(
      request: CreateIssueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createIssue",
        action: {
          (r: CreateIssueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createIssue(request: r, options: o)
        })
    }

    public func getIssue(
      request: GetIssueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.Issue {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIssue",
        action: {
          (r: GetIssueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.Issue
          in
          return try await self.inner.getIssue(request: r, options: o)
        })
    }

    public func listIssues(
      request: ListIssuesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListIssuesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listIssues",
        action: {
          (r: ListIssuesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListIssuesResponse
          in
          return try await self.inner.listIssues(request: r, options: o)
        })
    }

    public func updateIssue(
      request: UpdateIssueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateIssue",
        action: {
          (r: UpdateIssueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateIssue(request: r, options: o)
        })
    }

    public func deleteIssue(
      request: DeleteIssueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteIssue",
        action: {
          (r: DeleteIssueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteIssue(request: r, options: o)
        })
    }

    public func openIssue(
      request: OpenIssueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "openIssue",
        action: {
          (r: OpenIssueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.openIssue(request: r, options: o)
        })
    }

    public func closeIssue(
      request: CloseIssueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "closeIssue",
        action: {
          (r: CloseIssueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.closeIssue(request: r, options: o)
        })
    }

    public func getPullRequestComment(
      request: GetPullRequestCommentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.PullRequestComment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPullRequestComment",
        action: {
          (r: GetPullRequestCommentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.PullRequestComment
          in
          return try await self.inner.getPullRequestComment(request: r, options: o)
        })
    }

    public func listPullRequestComments(
      request: ListPullRequestCommentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListPullRequestCommentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPullRequestComments",
        action: {
          (r: ListPullRequestCommentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListPullRequestCommentsResponse
          in
          return try await self.inner.listPullRequestComments(request: r, options: o)
        })
    }

    public func createPullRequestComment(
      request: CreatePullRequestCommentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPullRequestComment",
        action: {
          (r: CreatePullRequestCommentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPullRequestComment(request: r, options: o)
        })
    }

    public func updatePullRequestComment(
      request: UpdatePullRequestCommentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePullRequestComment",
        action: {
          (r: UpdatePullRequestCommentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePullRequestComment(request: r, options: o)
        })
    }

    public func deletePullRequestComment(
      request: DeletePullRequestCommentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePullRequestComment",
        action: {
          (r: DeletePullRequestCommentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePullRequestComment(request: r, options: o)
        })
    }

    public func batchCreatePullRequestComments(
      request: BatchCreatePullRequestCommentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchCreatePullRequestComments",
        action: {
          (r: BatchCreatePullRequestCommentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchCreatePullRequestComments(request: r, options: o)
        })
    }

    public func resolvePullRequestComments(
      request: ResolvePullRequestCommentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "resolvePullRequestComments",
        action: {
          (r: ResolvePullRequestCommentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.resolvePullRequestComments(request: r, options: o)
        })
    }

    public func unresolvePullRequestComments(
      request: UnresolvePullRequestCommentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "unresolvePullRequestComments",
        action: {
          (r: UnresolvePullRequestCommentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.unresolvePullRequestComments(request: r, options: o)
        })
    }

    public func createIssueComment(
      request: CreateIssueCommentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createIssueComment",
        action: {
          (r: CreateIssueCommentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createIssueComment(request: r, options: o)
        })
    }

    public func getIssueComment(
      request: GetIssueCommentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.IssueComment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIssueComment",
        action: {
          (r: GetIssueCommentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.IssueComment
          in
          return try await self.inner.getIssueComment(request: r, options: o)
        })
    }

    public func listIssueComments(
      request: ListIssueCommentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecureSourceManagerV1.ListIssueCommentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listIssueComments",
        action: {
          (r: ListIssueCommentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecureSourceManagerV1.ListIssueCommentsResponse
          in
          return try await self.inner.listIssueComments(request: r, options: o)
        })
    }

    public func updateIssueComment(
      request: UpdateIssueCommentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateIssueComment",
        action: {
          (r: UpdateIssueCommentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateIssueComment(request: r, options: o)
        })
    }

    public func deleteIssueComment(
      request: DeleteIssueCommentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteIssueComment",
        action: {
          (r: DeleteIssueCommentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteIssueComment(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
