// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// UpdateBranchRuleRequest is the request to update a branchRule.
public struct UpdateBranchRuleRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  public var branchRule: BranchRule? = nil

  /// Optional. If set, validate the request and preview the review, but do not
  /// actually post it.  (https://google.aip.dev/163, for declarative friendly)
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Optional. Field mask is used to specify the fields to be overwritten in the
  /// branchRule resource by the update.
  /// The fields specified in the update_mask are relative to the resource, not
  /// the full request. A field will be overwritten if it is in the mask.
  /// The special value "*" means full replacement.
  public var updateMask: GoogleCloudWKT.FieldMask? = nil

  /// Initialize a new instance of `UpdateBranchRuleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateBranchRuleRequest().with { $0.branchRule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securesourcemanager.v1.UpdateBranchRuleRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
